# The parameters "input", "output", "reference" and "primer" are the absolute paths. Do not include the "/" at the end of the paths.
input          : "/blue/bphl-florida/dongyibo/Dev_Daytona_dengue/fastqs"
output    : "/blue/bphl-florida/dongyibo/Dev_Daytona_dengue/output"
reference      : "/blue/bphl-florida/dongyibo/Dev_Daytona_dengue/reference"
primer    : "/blue/bphl-florida/dongyibo/Dev_Daytona_dengue/primers"
# specify if input amplicons were fragmented. If yes, the parameter setting is "frag". If no, the parameter setting is "no_frag". (default: frag)
frag : "frag"

