# The parameters "input", "output", "reference" and "primer" are the absolute paths. Do not include the "/" at the end of the paths.
input          : "/blue/bphl-florida/dongyibo/Dev_Daytona_dengue/fastqs"
output    : "/blue/bphl-florida/dongyibo/Dev_Daytona_dengue/output"
reference      : "/blue/bphl-florida/dongyibo/Dev_Daytona_dengue/reference"
primer    : "/blue/bphl-florida/dongyibo/Dev_Daytona_dengue/primers"

